spring:
  datasource:
    url: jdbc:mysql://175.178.130.30/software_test_db?useSSL=false&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 1234

mybatis:
  type-aliases-package: com.example.databaseserver.entity
  mapper-locations: classpath:mapper/*.xml

server:
  port: 8082


