spring:
  datasource:
    url: jdbc:mysql://101.42.49.89/software_test_db?useSSL=false&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 1234
    hikari:
      maximum-pool-size: 10 # 设置最大连接数
      minimum-idle: 5 # 设置最小空闲连接数
      idle-timeout: 600000 # 设置连接的最大空闲时间（毫秒）
      max-lifetime: 1800000 # 设置连接的最大存活时间（毫秒）
      connection-timeout: 30000 # 设置获取连接的超时时间（毫秒）

mybatis:
  type-aliases-package: com.example.databaseserver.entity
  mapper-locations: classpath:mapper/*.xml

server:
  port: 8092

springdoc:
  swagger-ui:
    path: /docs.html

dubbo:
  application:
    name: database-server
    qos-port: 22223
  registry:
    address: nacos://${nacos_address:101.42.49.89}:8848
  protocol:
    name: dubbo
    port: 20892