dubbo:
  application:
    name: project-test-server
    logger: slf4j
    qos-port: 22229
  registry:
    address: nacos://${nacos.address:127.0.0.1}:8848
  protocol:
    name: dubbo
    port: 20879
  provider:
    timeout: 5000

server:
  port: 8090

spring:
  datasource:
    url: jdbc:mysql://175.178.130.30/software_test_db?useSSL=false&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 1234
    hikari:
      maximum-pool-size: 10 # 设置最大连接数
      minimum-idle: 5 # 设置最小空闲连接数
      idle-timeout: 600000 # 设置连接的最大空闲时间（毫秒）
      max-lifetime: 1800000 # 设置连接的最大存活时间（毫秒）
      connection-timeout: 30000 # 设置获取连接的超时时间（毫秒）
  application:
    name: project-test-server


springdoc:
  swagger-ui:
    path: /docs.html

logging:
  file:
    name: logs/spring-boot-application.log
  level:
    root: INFO
    org.springframework.web: DEBUG
  logback:
    rolling policy:
      total-size-cap: 100MB
      max-file-size: 10MB
      max-history: 30