#nacos:
#  address: 127.0.0.1
#  address: mse-5a242a20-p.nacos-ans.mse.aliyuncs.com
dubbo:
  application:
    logger: slf4j
    name: gateway-service
    qos-port: 22236
  registry:
    address: nacos://${nacos_address:101.42.49.89}:8848
    #    address: nacos://${nacos_address:127.0.0.1}:8848 # 本地nacos
    group: DEFAULT_GROUP # 服务分组，默认为 DEFAULT_GROUP
  protocol:
    name: dubbo
    port: 20886
  provider:
    timeout: 5000
    retries: 3 # 设置重试次数
    load balance: round robin # 负载均衡策略，可选值：random, roundrobin, leastactive
  consumer:
    check: false # 在启动时检查服务提供者是否可用
server:
  port: 8086

springdoc:
  swagger-ui:
    path: /swagger-ui.html

sa-token:
  # token 名称（同时也是 cookie 名称）
  token-name: satoken
  # token 有效期（单位：秒） 默认30天，-1 代表永久有效
  timeout: 2592000
  # token 最低活跃频率（单位：秒），如果 token 超过此时间没有访问系统就会被冻结，默认-1 代表不限制，永不冻结
  active-timeout: -1
  # 是否允许同一账号多地同时登录 （为 true 时允许一起登录, 为 false 时新登录挤掉旧登录）
  is-concurrent: true
  # 在多人登录同一账号时，是否共用一个 token （为 true 时所有登录共用一个 token, 为 false 时每次登录新建一个 token）
  is-share: true
  # token 风格（默认可取值：uuid、simple-uuid、random-32、random-64、random-128、tik）
  token-style: uuid
  # 是否输出操作日志
  is-log: true