dubbo:
  application:
    logger: slf4j
    name: task-service
    qos-port: 22235
  registry:
    address: nacos://${nacos_address:101.42.49.89}:8848
    #    address: nacos://${nacos_address:127.0.0.1}:8848 # 本地nacos
    group: DEFAULT_GROUP # 服务分组，默认为 DEFAULT_GROUP
  protocol:
    name: dubbo
    port: 20885
  provider:
    timeout: 5000
    retries: 3 # 设置重试次数
    load balance: round robin # 负载均衡策略，可选值：random, roundrobin, leastactive
  consumer:
    check: false # 在启动时检查服务提供者是否可用
server:
  port: 8085
spring:
  datasource:
    url: jdbc:mariadb://101.42.49.89/microservices?useSSL=false&serverTimezone=UTC
    driver-class-name: org.mariadb.jdbc.Driver
    username: root
    password: 1234
    hikari:
      maximum-pool-size: 10 # 设置最大连接数
      minimum-idle: 5 # 设置最小空闲连接数
      idle-timeout: 600000 # 设置连接的最大空闲时间（毫秒）
      max-lifetime: 1800000 # 设置连接的最大存活时间（毫秒）
      connection-timeout: 30000 # 设置获取连接的超时时间（毫秒）