server:
  port: 8091

spring:
  application:
    name: file-server

dubbo:
  application:
    name: file-server
    qos-port: 22222
  registry:
    address: N/A
  protocol:
    name: dubbo
    port: -1

springdoc:
  swagger-ui:
    path: /docs.html