server:
  port: 8091

spring:
  application:
    name: file-server

dubbo:
  application:
    name: file-server
    qos-port: 22222
  registry:
    address: nacos://${nacos_address:101.42.49.89}:8848
  protocol:
    name: dubbo
    port: 20891

springdoc:
  swagger-ui:
    path: /docs.html